#!/bin/bash

# Comment out this block if you're a sillyhead
if [[ $EUID -eq 0 ]]; then
  echo "Why are you running me as root, sillyhead?"
  exit 2
fi

NOTESWITHFLATS=(A Bb B C Db D Eb E F Gb G Ab)
NOTESWITHSHARPS=(A A# B C C# D D# E F F# G G#)

# Tunings
TUNING_PREFIX=Tuning_
DEFAULTTUNING=Standard
TUNINGS=(\
  Standard\
  "Drop D"\
)

# Scales
SCALE_PREFIX=Scale_
DEFAULTSCALE="A Minor Pentatonic"
SCALES=(\
  "A Minor Pentatonic"\
  "A Major Pentatonic"
)
Scale_A_Minor_Pentatonic=( A C D E G )
Scale_A_Major_Pentatonic=( A B C# E F# )

# Generate default config if needed
CONFIGFILE="$HOME/.config/retrojam/config"
CONFIGDIR=`dirname $CONFIGFILE`
if [ ! -d $CONFIGDIR ]; then
  mkdir -p $CONFIGDIR
fi
if [ ! -f $CONFIGFILE ]; then
  cat <<EOF > $CONFIGFILE
SHARPFLATDISPLAY=Sharps
CURRENTSCALE=A Minor Pentatonic
TUNING=$DEFAULTTUNING
EOF
fi

function retune_menu {
  clear
  PS3="Enter the number for your desired tuning: "
  select tuning_choice in "${TUNINGS[@]}"; do
    sed -i "s/^TUNING=.*/TUNING=$tuning_choice/" $CONFIGFILE
    break
  done
}

function choose_notes {
  sharpflatdisplay=`grep ^SHARPFLATDISPLAY $CONFIGFILE | sed 's/.*=//'`
  if [[ "$sharpflatdisplay" = "Sharps" ]]; then
    NOTES="${NOTESWITHSHARPS[@]}"
  else
    NOTES="${NOTESWITHFLATS[@]}"
  fi
}

function scale_menu {
  clear
  PS3="Enter the number for your desired scale: "
  select scale_choice in "${SCALES[@]}"; do
    sed -i "s/^CURRENTSCALE=.*/CURRENTSCALE=$scale_choice/" $CONFIGFILE
    break
  done
}

function translate_scale {
  sharpflatdisplay=`grep ^SHARPFLATDISPLAY $CONFIGFILE | sed 's/.*=//'`
  if [[ "$sharpflatdisplay" = "Flats" ]]; then
    echo $1
  fi
}

function main_menu {
  clear
  echo "\

██████╗ ███████╗████████╗██████╗  ██████╗      ██╗ █████╗ ███╗   ███╗
██╔══██╗██╔════╝╚══██╔══╝██╔══██╗██╔═══██╗     ██║██╔══██╗████╗ ████║
██████╔╝█████╗     ██║   ██████╔╝██║   ██║     ██║███████║██╔████╔██║
██╔══██╗██╔══╝     ██║   ██╔══██╗██║   ██║██   ██║██╔══██║██║╚██╔╝██║
██║  ██║███████╗   ██║   ██║  ██║╚██████╔╝╚█████╔╝██║  ██║██║ ╚═╝ ██║
╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝  ╚════╝ ╚═╝  ╚═╝╚═╝     ╚═╝"

  tuning=`grep ^TUNING $CONFIGFILE | sed 's/.*=//'`
  sharpflatdisplay=`grep ^SHARPFLATDISPLAY $CONFIGFILE | sed 's/.*=//'`
  scale=`grep ^CURRENTSCALE $CONFIGFILE | sed 's/.*=//'`
  scale_suffix=`echo $scale | tr ' ' '_'`
  eval scale_alias=( \"\${${SCALE_PREFIX}${scale_suffix}[@]}\" )

  if [[ $sharpflatdisplay = Flats ]]; then
    scale_index=0
    for scale_note in ${scale_alias[@]}; do
      echo $scale_note | grep '#' > /dev/null
      if [ $? -eq 0 ]; then
        index=0
        for val in ${NOTESWITHSHARPS[@]}; do
          if [[ "$val" = "$scale_note" ]]; then
            scale_alias[$scale_index]="${NOTESWITHFLATS[$index]}"
          fi
          index=$((index+1))
        done
      fi
      scale_index=$((scale_index+1))
    done
  fi
  
  echo "Your currently selected scale is $scale (${scale_alias[@]})"
  echo "Your currently selected tuning is $tuning."

  PS3="Enter the number for your menu selection: "
  select choice in \
    Play\
    "Change Scale"\
    Retune\
    "Toggle: Show Sharp or Flat Notes. Currently showing $sharpflatdisplay ($NOTES)"\
    Quit; do

    case $choice in
      Play)
        break
        ;;
      "Change Scale") 
	scale_menu
	break
        ;;
      Retune)
        retune_menu
	break
        ;;
"Toggle: Show Sharp or Flat Notes. Currently showing $sharpflatdisplay ($NOTES)")
        if [[ "$sharpflatdisplay" = "Sharps" ]]; then 
	  sharpflatdisplay="Flats"
	else
	  sharpflatdisplay="Sharps"
	fi
        sed -i "s/^SHARPFLATDISPLAY=.*/SHARPFLATDISPLAY=$sharpflatdisplay/" $CONFIGFILE 2> /tmp/b
	choose_notes
	echo $NOTES > /tmp/a
	break
	;;
      Quit)
        exit 0
        ;;
      *)
        echo "Invalid option $REPLY"
        ;;
    esac
  done
}

choose_notes
while : ;do
  main_menu
done
