#!/bin/bash

# Comment out this block if you're a sillyhead
if [[ $EUID -eq 0 ]]; then
  echo "Why are you running me as root, sillyhead?"
  exit 2
fi

NOTESWITHFLATS=(A Bb B C Db D Eb E F Gb G Ab)
NOTESWITHSHARPS=(A A# B C C# D D# E F F# G G#)

# Tunings
DEFAULTTUNING=Standard
TUNINGS=(Standard DropD)

# Scales

# Generate default config if needed
CONFIGFILE="$HOME/.config/retrojam/config"
CONFIGDIR=`dirname $CONFIGFILE`
if [ ! -d $CONFIGDIR ]; then
  mkdir -p $CONFIGDIR
fi
if [ ! -f $CONFIGFILE ]; then
  cat <<EOF > $CONFIGFILE
SHARPFLATDISPLAY=Sharps
TUNING=$DEFAULTTUNING
EOF
fi

function retune_menu {
  clear
  PS3="Enter the number for your desired tuning: "
  select tuning in "${TUNINGS[@]}"; do
    sed -i "s/^TUNING=.*/TUNING=$tuning/" $CONFIGFILE
    break
  done
}

function choose_notes {
  sharpflatdisplay=`grep ^SHARPFLATDISPLAY $CONFIGFILE | sed 's/.*=//'`
  if [[ "$sharpflatdisplay" = "Sharps" ]]; then
    NOTES="${NOTESWITHSHARPS[@]}"
  else
    NOTES="${NOTESWITHFLATS[@]}"
  fi
}
  

function main_menu {
  clear
  echo "\

██████╗ ███████╗████████╗██████╗  ██████╗      ██╗ █████╗ ███╗   ███╗
██╔══██╗██╔════╝╚══██╔══╝██╔══██╗██╔═══██╗     ██║██╔══██╗████╗ ████║
██████╔╝█████╗     ██║   ██████╔╝██║   ██║     ██║███████║██╔████╔██║
██╔══██╗██╔══╝     ██║   ██╔══██╗██║   ██║██   ██║██╔══██║██║╚██╔╝██║
██║  ██║███████╗   ██║   ██║  ██║╚██████╔╝╚█████╔╝██║  ██║██║ ╚═╝ ██║
╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝  ╚════╝ ╚═╝  ╚═╝╚═╝     ╚═╝"

  TUNING=`grep ^TUNING $CONFIGFILE | sed 's/.*=//'`
  sharpflatdisplay=`grep ^SHARPFLATDISPLAY $CONFIGFILE | sed 's/.*=//'`
  echo $NOTES
  echo "Your currently selected tuning is $TUNING."

  PS3="Enter the number for your menu selection: "
  select choice in Play Retune "Toggle: Show Sharp or Flat Notes: $sharpflatdisplay ($NOTES)" Quit; do
    case $choice in
      Play)
	break
        ;;
      Retune)
        retune_menu
	break
        ;;
"Toggle: Show Sharp or Flat Notes: $sharpflatdisplay ($NOTES)")
        if [[ "$sharpflatdisplay" = "Sharps" ]]; then 
	  sharpflatdisplay="Flats"
	else
	  sharpflatdisplay="Sharps"
	fi
        sed -i "s/^SHARPFLATDISPLAY=.*/SHARPFLATDISPLAY=$sharpflatdisplay/" $CONFIGFILE 2> /tmp/b
	choose_notes
	echo $NOTES > /tmp/a
	break
	;;
      Quit)
        exit 0
        ;;
      *)
        echo "Invalid option $REPLY"
        ;;
    esac
  done
}

choose_notes
while : ;do
  main_menu
done
