#!/bin/bash

# Comment out this block if you're a sillyhead
if [[ $EUID -eq 0 ]]; then
  echo "Why are you running me as root, sillyhead?"
  exit 2
fi

NOTESWITHFLATS=(A Bb B C Db D Eb E F Gb G Ab)
NOTESWITHSHARPS=(A A# B C C# D D# E F F# G G#)

# Tunings
TUNING_PREFIX=Tuning_
DEFAULTTUNING=Standard
TUNINGS=(\
  Standard\
  "Drop D"\
)

# Root Notes
DEFAULTROOTNOTE=C

# Scale Types
DEFAULTSCALETYPE="Major"
SCALETYPES=(\
  "Major (Ionian)"
  "Major Pentatonic"
  "Minor Pentatonic"\
)
C_Major=( C D E F G A B )
A_Minor_Pentatonic=( A C D E G )
A_Major_Pentatonic=( A B C# E F# )

# Generate default config if needed
CONFIGFILE="$HOME/.config/retrojam/config"
CONFIGDIR=`dirname $CONFIGFILE`
if [ ! -d $CONFIGDIR ]; then
  mkdir -p $CONFIGDIR
fi
if [ ! -f $CONFIGFILE ]; then
  cat <<EOF > $CONFIGFILE
ROOTNOTE=$DEFAULTROOTNOTE
SCALETYPE=$DEFAULTSCALETYPE
SHARPFLATDISPLAY=Sharps
TUNING=$DEFAULTTUNING
EOF
fi

function retune_menu {
  clear
  PS3="Enter the number for your desired tuning: "
  select tuning_choice in "${TUNINGS[@]}"; do
    sed -i "s/^TUNING=.*/TUNING=$tuning_choice/" $CONFIGFILE
    break
  done
}

function choose_notes {
  sharpflatdisplay=`grep ^SHARPFLATDISPLAY $CONFIGFILE | sed 's/.*=//'`
  if [[ "$sharpflatdisplay" = "Sharps" ]]; then
    NOTES="${NOTESWITHSHARPS[@]}"
  else
    NOTES="${NOTESWITHFLATS[@]}"
  fi
}

function scale_type_menu {
  clear
  PS3="Enter the number for your desired scale type: "
  select scale_type_choice in "${SCALETYPES[@]}"; do
    sed -i "s/^SCALETYPE=.*/SCALETYPE=$scale_type_choice/" $CONFIGFILE
    break
  done
}

function root_note_menu {
  clear
  choose_notes
  PS3="Enter the number for your desired root note: "
  select root_note_choice in "${NOTES[@]}"; do
    sed -i "s/^ROOTNOTE=.*/ROOTNOTE=$root_note_choice/" $CONFIGFILE
    break
  done
}
  
function main_menu {
  clear
  echo "\

██████╗ ███████╗████████╗██████╗  ██████╗      ██╗ █████╗ ███╗   ███╗
██╔══██╗██╔════╝╚══██╔══╝██╔══██╗██╔═══██╗     ██║██╔══██╗████╗ ████║
██████╔╝█████╗     ██║   ██████╔╝██║   ██║     ██║███████║██╔████╔██║
██╔══██╗██╔══╝     ██║   ██╔══██╗██║   ██║██   ██║██╔══██║██║╚██╔╝██║
██║  ██║███████╗   ██║   ██║  ██║╚██████╔╝╚█████╔╝██║  ██║██║ ╚═╝ ██║
╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝  ╚════╝ ╚═╝  ╚═╝╚═╝     ╚═╝"

  tuning=`grep ^TUNING $CONFIGFILE | sed 's/.*=//'`
  rootnote=`grep ^ROOTNOTE $CONFIGFILE | sed 's/.*=//'`
  sharpflatdisplay=`grep ^SHARPFLATDISPLAY $CONFIGFILE | sed 's/.*=//'`
  scaletype=`grep ^SCALETYPE $CONFIGFILE | sed 's/.*=//'`
  scale_suffix=`echo $scaletype | tr ' ' '_' | sed 's/(.*//'`

  eval scale_alias=( \"\${${rootnote}_${scale_suffix}[@]}\" )
  
  if [[ $sharpflatdisplay = Flats ]]; then
    scale_index=0
    for scale_note in ${scale_alias[@]}; do
      echo $scale_note | grep '#' > /dev/null
      if [ $? -eq 0 ]; then
        index=0
        for val in ${NOTESWITHSHARPS[@]}; do
          if [[ "$val" = "$scale_note" ]]; then
            scale_alias[$scale_index]="${NOTESWITHFLATS[$index]}"
          fi
          index=$((index+1))
        done
      fi
      scale_index=$((scale_index+1))
    done
  fi
  
  echo ""
  echo "Current Settings:"
  echo "================="
  echo "Root Note: $rootnote"
  echo "Scale Type: $scaletype (${scale_alias[@]})"
  echo "Tuning: $tuning"
  echo ""

  echo "Main menu"
  echo "========="
  PS3="Enter the number for your menu selection: "
  select choice in \
    Play\
    "Change Root Note"\
    "Change Scale Type"\
    Retune\
    "Toggle: Show Sharp or Flat Notes. Currently showing $sharpflatdisplay ($NOTES)"\
    Quit; do

    case $choice in
      Play)
        break
        ;;
      "Change Root Note")
        root_note_menu
        break
        ;;
      "Change Scale Type") 
	scale_type_menu
	break
        ;;
      Retune)
        retune_menu
	break
        ;;
"Toggle: Show Sharp or Flat Notes. Currently showing $sharpflatdisplay ($NOTES)")
        if [[ "$sharpflatdisplay" = "Sharps" ]]; then 
	  sharpflatdisplay="Flats"

	else
	  sharpflatdisplay="Sharps"
	fi
        sed -i "s/^SHARPFLATDISPLAY=.*/SHARPFLATDISPLAY=$sharpflatdisplay/" $CONFIGFILE 2> /tmp/b
	choose_notes

	# Translate flat root note to sharp
        echo $rootnote | grep 'b' > /dev/null
	if [ $? -eq 0 ]; then
          index=0
          for val in ${NOTESWITHFLATS[@]}; do
            if [[ "$val" = "$rootnote" ]]; then
              rootnote="${NOTESWITHSHARPS[$index]}"
	      sed -i 's/^ROOTNOTE=.*/ROOTNOTE=$rootnote/' $CONFIGFILE
	      break
	    fi
            index=$((index+1))   
	  done
	fi
	
	# Translate sharp root note to flat
        echo $rootnote | grep '#' > /dev/null
	if [ $? -eq 0 ]; then
          index=0
          for val in ${NOTESWITHSHARPS[@]}; do
            if [[ "$val" = "$rootnote" ]]; then
              rootnote="${NOTESWITHFLATS[$index]}"
	      sed -i 's/^ROOTNOTE=.*/ROOTNOTE=$rootnote/' $CONFIGFILE
	      break
	    fi
            index=$((index+1))   
	  done
	fi
	break
	;;
      Quit)
        exit 0
        ;;
      *)
        echo "Invalid option $REPLY"
        ;;
    esac
  done
}

choose_notes
while : ;do
  main_menu
done
